ous:
    hosts:
        centos71:
          ansible_host: 192.168.122.54
        centos72:
          ansible_host: 192.168.122.19

elasticsearch:
    hosts:
        centos71:
            elasticsearch_role: masterdata
            elasticsearch_nodename: elsnode01
        centos72:
            elasticsearch_role: coordinator
            elasticsearch_nodename: elsnode02
    vars:
        elasticsearch_cluster: els-cluster
        elasticsearch_hostip: "{{ ansible_host }}"
        elasticsearch_port: '9200'
        elasticsearch_protocol: 'http'
        elasticsearch_mininimum_master_nodes: 1

kibana:
    hosts:
        centos72:

all:
    vars:
        ansible_user: root
        elasticsearch_master_endpoints: "{{ groups['elasticsearch'] | map('extract', hostvars) | selectattr('elasticsearch_role', 'equalto', 'masterdata') | mapelsurl | list }}"
        elasticsearch_master_ips:  "{{ groups['elasticsearch'] | map('extract', hostvars) | selectattr('elasticsearch_role', 'equalto', 'masterdata') | mapelsips | list }}"
        elasticsearch_coordinator_endpoints: "{{ groups['elasticsearch'] | map('extract', hostvars) | selectattr('elasticsearch_role', 'equalto', 'coordinator') | mapelsurl | list }}"
  



